version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: clickup-backup-agent
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=UTC
      - N8N_LOG_LEVEL=info
      - N8N_METRICS=true
      - N8N_DIAGNOSTICS_ENABLED=false
    volumes:
      - n8n_data:/home/node/.n8n
      - ./clickup-backup-workflow.json:/home/node/.n8n/workflows/clickup-backup-workflow.json
      - ./credentials:/home/node/.n8n/credentials
    env_file:
      - .env
    networks:
      - clickup-backup-network

  # Optional: Add a monitoring service
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=86400
    networks:
      - clickup-backup-network

volumes:
  n8n_data:
    driver: local

networks:
  clickup-backup-network:
    driver: bridge